service: blog
runtime: go111

env_variables:
  GOLANGORG_CHECK_COUNTRY: true

default_expiration: "7d"

# Keep these static file handlers in sync with blog.go.
# They're here for improved latency across global regions.
handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /fonts.css
  static_files: static/fonts.css
  upload: static/fonts.css
  secure: always
- url: /fonts
  static_dir: static/fonts
  http_headers:
    Content-Type: application/font-woff
  secure: always
